# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dc77e40e7bdce566911a0fd9363dc296"
name = "choco-app"
handle = "choco-app-32"
application_url = "https://supervisor-ho-relevant-meeting.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-707211d4.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://supervisor-ho-relevant-meeting.trycloudflare.com/auth/callback",
  "https://supervisor-ho-relevant-meeting.trycloudflare.com/auth/shopify/callback",
  "https://supervisor-ho-relevant-meeting.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
